version: '3.8'

services:
  db:
    image: postgres:13.7
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: app
      POSTGRES_DB: app

    ports:
      - '5435:5432'

    volumes:
      - app-volume:/var/lib/postgresql/data
      - ./init_db:/init_db

volumes:
  app-volume: